import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignOutButton,
  SignUpButton,
  SignedIn,
  SignedOut,
} from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <header>
            <div className="flex items-center justify-between p-5">
              <h1 className="text-4xl font-bold">LOGO</h1>
              {/* Content to show when user is signed out */}
              <SignedOut>
                <div className="flex item-center space-x-5">
                  <SignUpButton mode="modal" />
                  <SignInButton mode="modal" />
                </div>
              </SignedOut>
              {/* Content to show when user is signed in. */}
              <SignedIn>
                {/* Add your header menu */}
                {/* Custom signOut button. You can customise it */}
                <SignOutButton redirectUrl="/" />
              </SignedIn>
            </div>
          </header>
          {/* Main content */}
          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
